#!/usr/bin/perl
use warnings;
use strict;

=problem11
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=cut

my $triagle   = 1;
my $increment = 1;
my $factors   = 0;
my $factors_cache = {};

while( $factors < 500 ) {

    $increment++;
    $triagle = $triagle + $increment;

    $factors = get_factors( $triagle );

}

print "$triagle -> $factors\n";

sub get_factors_cache {
    my $number = shift;
    my $second = shift//$number;

    return $factors_cache->{$number} if exists $factors_cache->{$number};

    return 0 unless $second;

    my $factors = ( ( get_factors_cache($number,$second-1) ) + ( $number % $second == 0 ? 1 : 0 ) );

    $factors_cache->{$number} = $factors;
    $factors;
}

sub get_factors {
    my $number  = shift;
    my $factors = 0;

    for ( my $divisor = $number; $divisor > 0; $divisor-- ) {

        $factors++ unless $number % $divisor;

    }

    $factors;
}


